# Generated by Django 5.0.3 on 2024-03-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Gift title', max_length=255)),
                ('gift', models.FileField(help_text='Gift file', upload_to='gifts/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title', max_length=255)),
                ('lesson', models.FileField(help_text='Video', upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('course', models.ForeignKey(help_text='Course', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='orm_app.course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
