# Generated by Django 3.2.25 on 2024-04-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_course_gift_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_description', models.TextField(help_text="Admin haqida ma'lumot", verbose_name='Admin description')),
                ('admin1_telegram_link', models.TextField(help_text='Birinchi Admin telegram link', verbose_name='Admin 1 telegram link')),
                ('admin2_telegram_link', models.TextField(help_text='Ikkinchi Admin telegram link', verbose_name='Admin 2 telegram link')),
                ('channel_link', models.TextField(help_text='Kanal link, Bepul Darslar uchun', verbose_name='Channel link')),
            ],
            options={
                'verbose_name': 'AdminInfo',
                'verbose_name_plural': 'AdminInfo',
            },
        ),
        migrations.CreateModel(
            name='ResultExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Natija Matni', verbose_name='Text')),
                ('exam_file', models.FileField(help_text='Exam file', upload_to='exams/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at', null=True)),
            ],
            options={
                'verbose_name': 'ResultExam',
                'verbose_name_plural': 'ResultExams',
            },
        ),
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.TextField(help_text='Gift uchun nomi yoki text uchun joy!', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.FileField(help_text='Sizning darsingiz', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(help_text='Mazvu nomi yoki text uchun joy!', verbose_name='Title'),
        ),
    ]
