# Generated by Django 3.2.25 on 2024-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0004_auto_20240427_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelessontext',
            name='image',
            field=models.ImageField(default=1, help_text='Free Lesson Rasmi', upload_to='free_lesson_image/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='image',
            field=models.ImageField(help_text='Admin rasmi', upload_to='user_image/', verbose_name='Image'),
        ),
    ]
